apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nww2pcysf-go 
  janus-idp.io/tekton: nww2pcysf-go
  backstage.io/kubernetes-id: nww2pcysf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nww2pcysf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml