apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nww2pcysf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nww2pcysf-go 
  name: nww2pcysf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nww2pcysf-go 
